GET http://localhost:3000/api/todos
Content-Type: application/json

###

POST http://localhost:3000/api/todos
Content-Type: application/json

{
    "text": "Buy video games"
}

###

PUT http://localhost:3000/api/todos/1
Content-Type: application/json

{
    "text": "Actulizado",
    "completedAt": "2023-10-12"
}

###

DELETE http://localhost:3000/api/todos/1
Content-Type: application/json
